### ISSUE TITLE
How to use controller with API (and others HTTP actions)

### ISSUE THREAD

**Issue by fuyangli** [shameerc/slim-skeleton#1]
I've seen some slim skeletons that use controllers. But, how can I strucutre my application using controllers if I have several HTTP actions to that route?
e.g:

GET in /login returns the login page
POST in /login does the login routine

Will I have to write an controller to GET and other to POST of the same page?

**Comment by shameerc** [comment]
If you want to follow [ADR](https://github.com/pmjones/adr), you need to have an action controller for both GET and POST and give the controllers some meaningful names like [this](https://github.com/pmjones/adr/tree/master/example-code/Web/Blog/Action).  
Hope that makes sense.
